[theme]
base = "dark"
primaryColor = "#F5F5F5"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#141414"
textColor = "#F5F5F5"
font = "sans serif"

[server]
websocketPingInterval = 120
disconnectedSessionTTL = 120