[theme]
base = "dark"
primaryColor = "#C8102E"
backgroundColor = "#0F0F0F"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#F8F1E9"
font = "sans serif"

[server]
websocketPingInterval = 120
disconnectedSessionTTL = 120
